### ISSUE TITLE
Improve relation and meta-relation rendering.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/reductive_analysis_app#240]
While a comprehensive implementation of #20 remains the "holy grail," we can meanwhile pursue a more modest solution to the issue of overlapping slurs and unwieldy metarelations.

As a first step, we could use slur-like (Bezier) curves for relations, adhering to the right-hand column of our [Figma prototype](https://www.figma.com/file/t5wPZQ1duIYggtKKi1U9Qq/DCML).

Steps:

- [X] Replace capsules with slurs.
- [x] Use simple heuristics for collision reduction.
- [x] Stack multiple slurs between the same endpoints (see Figma)
- [x] For every relation that is member of at least one metarelation, implement a metarelation toggle in the shape of a circular mini-button, as shown in the Figma.
- [ ] ...

This issue addresses #239.

**Comment by yrammos** [comment]
@arundhatibala let us keep track of this feature here.

**Comment by yrammos** [comment]
@yinanazhou This discussion refers to an idea for meta-relations, which I was discussing with a student assistant a few months ago. Let’s resume this discussion when you get to meta-relations. (Simple relations are higher-priority for now.) Thanks.

**Comment by yinanazhou** [comment]
- [x] #258 
- [x] #261

**Comment by yrammos** [comment]
@yinanazhou are we using this issue for the new design?

![Image](https://github.com/user-attachments/assets/e89940fc-4ebc-4632-beae-1a6d1fee26e4)

**Comment by yrammos** [comment]
Never mind, @yinanazhou, I’ll close this and open a new one.
